const string UTOPIA_AIRDROP_ROOT_FOLDER = "$profile:Utopia_Airdrop\\";
const string UTOPIA_AIRDROP_CONFIG_FOLDER = UTOPIA_AIRDROP_ROOT_FOLDER;
const string UTOPIA_AIRDROP_CONFIG_FILE = UTOPIA_AIRDROP_ROOT_FOLDER + "UtopiaAirdropSettings.json";

const string UTOPIA_AIRDROP_VERSION = "1.1.3";


const string UTOPIA_AIRDROP_LOG_FOLDER = UTOPIA_AIRDROP_ROOT_FOLDER;
const string UTOPIA_AIRDROP_LOGGER_CONFIG_DIR = UTOPIA_AIRDROP_LOG_FOLDER ;
const string UTOPIA_AIRDROP_LOGGER_CONFIG_FILE = UTOPIA_AIRDROP_LOGGER_CONFIG_DIR;
const string UTOPIA_AIRDROP_LOGGER_LOG_DIR = UTOPIA_AIRDROP_LOG_FOLDER;
const string UTOPIA_AIRDROP_LOGGER_LOG_FILE = UTOPIA_AIRDROP_LOGGER_LOG_DIR;

enum EUtopiaContainerType
{
    CRATE,
    HACKEABLE_CRATE,
    CAR_CONTAINER
};